config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "images#index"
  resources :images, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :upper_image, ImageUploader
  mount_uploader :down_image, ImageUploader

  skip_callback :commit, :after, :remove_previously_stored_upper_image
  skip_callback :commit, :after, :remove_previously_stored_down_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :images
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    if user_signed_in?
      search_user_images
    end
  end

  def new
    @image = Image.new
  end

  def create
    image_present
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    image = Image.find(params[:id])
    if params[:image].present?
      image.update(image_params)
      redirect_to user_path(current_user.id)
    else
      destroy
    end
  end

  def destroy
    image = Image.find(params[:id])
    image.delete
    redirect_to user_path(current_user.id)
  end

  private

  def image_params
    params.require(:image).permit(:upper_image, :down_image).merge(user_id: current_user.id)
  end

  def move_to_new
    redirect_to new_image_path
  end

  def search_user_images
    @images = Image.where(user_id: current_user.id).includes(:user)
    if @images.present?
      @user_images = @images.select("id", "upper_image", "down_image", "user_id")
      @upper_images = @user_images.where.not(upper_image: nil)
      @down_images = @user_images.where.not(down_image: nil)
      if @upper_images.present? && @down_images.present?
        @related_upper_image = @upper_images.shuffle.first
        @related_down_image = @down_images.shuffle.first
      else
        move_to_new
      end
    else
      move_to_new
    end
  end

  def image_present
    if params[:image].present?
      if image_params[:upper_image].present? or image_params[:down_image].present?
        Image.create(image_params)
      end
    end
    move_to_new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    search_user_images
    user = User.find(params[:id])
  end

  private

  def image_params
    params.require(:image).permit(:upper_image, :down_image).merge(user_id: current_user.id)
  end

  def search_user_images
    @images = Image.where(user_id: current_user.id).includes(:user)
    @upper_images = @images.select("id", "upper_image", "user_id").where.not(upper_image: nil)
    @down_images = @images.select("id", "down_image", "user_id").where.not(down_image: nil)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/down_image/new.html.erb
<h1>DownImage#new</h1>
<p>Find me in app/views/down_image/new.html.erb</p>

app/views/images/_form.html.erb
<%= form.hidden_field :image_cache %>

<div class="image_new upper_image_new">
  <div class="btns">
    <label class: image_box upper_image_box>
      <h2>SHIRTを選択</h2>
      <%= form.file_field :upper_image, {class: "select_imagefile", id: "select_upper_image"}%>
    </label>
  </div>
  <% if @image.upper_image.present? %>
    <%= image_tag(@image.upper_image_url, id: "upper_image") %>
  <% else %>
    <div class="image_preview" id="upper_image">左のボタンを押して<br>ファイルを選択<br>してください<br></div>
  <% end %>
</div>

<div class="image_new down_image_new">
  <div class="btns">
    <label class: image_box down_image_box>
      <h2>PANTSを選択</h2>
      <%= form.file_field :down_image, {class: "select_imagefile", id: "select_down_image"}  %>
    </label>
    <label>
      <h2 class="delete_btn">選択を解除</h2>
    </label>
  </div>
  <% if @image.down_image.present? %>
    <%= image_tag(@image.down_image_url, id: "down_image") %>
  <% else %>
    <div class="image_preview"  id="down_image">左のボタンを押して<br>ファイルを選択<br>してください<br></div>
  <% end %>
</div>

app/views/images/edit.html.erb
<div class="form">
  <%= form_with(model: @image, local: true) do |form| %>
    <div class="vertical_form">
    
      <%= cache @image do %>
        <%= render partial: "form", locals: {form: form} %>
      <% end %>

      <div class="submit_btn_bottom new_submit_btn">
        <%= form.submit "更新する" %>
      </div>
      <p class="submit_btn_bottom delete_submit_btn">
        <%= link_to "削除する", image_path(@image.id), method: :delete %>
      </p>

    </div>

    <div class="submit_btn_right new_submit_btn">
      <%= form.submit "更新する" %>
    </div>
    <p class="submit_btn delete_submit_btn" id="delete_submit_btn_right">
      <%= link_to "削除する", image_path(@image.id), method: :delete %>
    </p>
  <% end %>
</div> 

app/views/images/index.html.erb
<span class="setting">
  <% if user_signed_in? %>
    <div class="vertical_index">
      <div class="setting_image upper-image">
        <%= image_tag @related_upper_image.upper_image.url %>
      </div>
      <div class ="setting_image down-image">
        <%= image_tag @related_down_image.down_image.url %>
      </div>
      <div class="set_btn" id="set_btn_bottom">
      <label>
        <button type="button" value="change_btn" class="change_btn"><a href="/">CHANGE</a></button>
        </label>
      </div>
    </div>
    <div class="set_btn" id="set_btn_right">
    <label>
      <button type="button" value="change_btn" class="change_btn"><a href="/">CHANGE</a></button>
      </label>
    </div>
  <%else%>
    <div>
    </div>
  <% end %>
</span>

app/views/images/new.html.erb
<div class="form">

  <%= form_with(model: @image, local: true) do |form| %>
    <div class="vertical_form">
      <%= render partial:"form", locals:{form:form} %>
      <div class="submit_btn_bottom new_submit_btn">
        <%= form.submit "登録する" %>
      </div>
    </div>
    <div class="submit_btn_right new_submit_btn">
      <%= form.submit "登録する" %>
    </div>
  <%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionAutoset</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <% if user_signed_in?%>
          <div class="user_nav grid-6">
            <span>
              <ul class="user__info">
                <li>
                  <%= link_to "ユーザー名： #{current_user.name}", root_path, class: "root"%>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "log-out"%>
                </li>
              </ul>
            </span> 
          </div>
          <div class="dropdown">
            <ul class="dropdown_btn">
              <button class="dropdown_btn menu_btn">MENU</button>
              <li class="menulist">
                <a href="/"><button class="menu edit_btn">トップへ</button></a>
                <a href="/users/<%= current_user.id %>"><button class="menu mypage_btn">マイページ</button></a>
                <a href="/images/new"><button class="menu new_btn">登録</button></a>
              </li>
            </ul>
          </div>
        <% else %>
          <div class="grid-6">
            <span>
              <ul class="user__info">
                <li>
                  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
                  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
                </li>
              </ul>
            </span> 
          </div>
        <% end%>
      </div>
    </header>
    <div class="body">
    <div class="main">
    <%= yield %>
    </div>
    </div>
<div class="footer">Fashion Auto Setting.</div>
  </body>
</html>

app/views/users/show.html.erb
<div class="user_images user_upper_images">
  <h2 class="user_images_headline" id="user_upper_images_headline">
    SHIRT
  </h2>
  <ul class="user_image_list user_upper_image_list">
    <% @upper_images.each do |upper_image|%>
      <li class="user_image user_upper_image">
        <%= image_tag(upper_image.upper_image_url, width: 100) %>
        <label>
        <div class="image_btn">
          <%= link_to '編集', edit_image_path(upper_image.id) %>
        </div>
        </label>
      </li>
    <%end%>
  </ul>
</div>

<div class="user_images user_down_images">
  <h2 class="user_images_headline" id="user_down_images_headline">
    PANTS
  </h2>
  <ul class="user_image_list user_down_image_list">
    <% @down_images.each do |down_image|%>
      <li class="user_image user_down_image">
        <%= image_tag(down_image.down_image_url, width: 100)%>
        <div class="image_btn">
          <%= link_to '編集', edit_image_path(down_image.id) %>
        </div>
      </li>
    <%end%>
  </ul>
</div>